apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "memcached.fullname" . }}-hook-run-shell
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "memcached.fullname" . }}-hook-run-shell
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "memcached.fullname" . }}-preinstall-run-shell
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.global.arch }}
                - {{ . }}
                {{- end }}
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
        - name: {{ template "memcached.fullname" . }}-preinstall-run-shell
          image: "ubuntu:latest"
          command:
          - /redisusersecret/create-secret.sh
          volumeMounts:
          - mountPath: "/redisusersecret"
            name: redis-secret-config
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
      hostIPC: false
      hostNetwork: false
      hostPID: false
      restartPolicy: Never
      volumes:
      - name: redis-secret-config
        configMap:
          name: {{ template "memcached.fullname" . }}-create-redis-secret
          defaultMode: 0755
