apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "memcached.fullname" . }}-postinstall-shell
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "memcached.fullname" . }}-postinstall-shell
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  create-secret.sh: |
    #!/bin/sh
    if  (!(kubectl get secret {{ .Release.Name }}-post-install-shell));
    then
      kubectl create secret generic {{ .Release.Name }}-post-install-shell --from-literal=redispwd=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1) --dry-run -o yaml | kubectl apply -f -
    fi
