apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "memcached.fullname" . }}-preinstall-create-shell
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "memcached.fullname" . }}-preinstall-create-shell
  annotations:
    helm.sh/hook: pre-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
data:
  create-file.sh: |
    #!/bin/sh
    echo "hello" > {{ .Release.Name }}-post-install-shell
    sleep 30
