apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "memcached.fullname" . }}-preinstall-create-shell
    chart: {{.Chart.Name}}-{{.Chart.Version}}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "memcached.fullname" . }}-preinstall-create-shell
  annotations:
    helm.sh/hook: pre-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
data:
  create-file.sh: |
    #!/bin/sh
    if  (!(kubectl get secret {{ .Release.Name }}-redisgraph-user-secrets));
    then
      kubectl create secret generic {{ .Release.Name }}-redisgraph-user-secrets --from-literal=redispwd=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1) --dry-run -o yaml | kubectl apply -f -
    fi
    sleep 30
